// "DoorSideFrame.h" generated by "Obj2Header.exe" [Version 1.9d] Author: L.Norri Fullsail University.
// Data is converted to left-handed coordinate system and UV data is V flipped for Direct3D/Vulkan.
// The companion file "DoorSideFrame.h2b" is a binary dump of this format(-padding) for more flexibility.
// Loading *.h2b: read version, sizes, handle strings(max len 260) by reading until null-terminated.
/***********************/
/*  Generator version  */
/***********************/
#ifndef _DoorSideFrame_version_
const char DoorSideFrame_version[4] = { '0','1','9','d' };
#define _DoorSideFrame_version_
#endif
/************************************************/
/*  This section contains the model's size data */
/************************************************/
#ifndef _DoorSideFrame_vertexcount_
const unsigned DoorSideFrame_vertexcount = 48;
#define _DoorSideFrame_vertexcount_
#endif
#ifndef _DoorSideFrame_indexcount_
const unsigned DoorSideFrame_indexcount = 72;
#define _DoorSideFrame_indexcount_
#endif
#ifndef _DoorSideFrame_materialcount_
const unsigned DoorSideFrame_materialcount = 2; // can be used for batched draws
#define _DoorSideFrame_materialcount_
#endif
#ifndef _DoorSideFrame_meshcount_
const unsigned DoorSideFrame_meshcount = 2;
#define _DoorSideFrame_meshcount_
#endif
/************************************************/
/*  This section contains the raw data to load  */
/************************************************/
#ifndef __OBJ_VEC3__
typedef struct _OBJ_VEC3_
{
	float x,y,z; // 3D Coordinate.
}OBJ_VEC3;
#define __OBJ_VEC3__
#endif
#ifndef __OBJ_VERT__
typedef struct _OBJ_VERT_
{
	OBJ_VEC3 pos; // Left-handed +Z forward coordinate w not provided, assumed to be 1.
	OBJ_VEC3 uvw; // D3D/Vulkan style top left 0,0 coordinate.
	OBJ_VEC3 nrm; // Provided direct from obj file, may or may not be normalized.
}OBJ_VERT;
#define __OBJ_VERT__
#endif
#ifndef _DoorSideFrame_vertices_
// Raw Vertex Data follows: Positions, Texture Coordinates and Normals.
const OBJ_VERT DoorSideFrame_vertices[48] =
{
	{	{ -0.418517f, 0.372713f, -0.065334f },	{ 0.086543f, 0.906709f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.418517f, 0.362481f, -0.065334f },	{ 0.086543f, 0.536007f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.418517f, 0.362481f, -0.056226f },	{ 0.416505f, 0.536008f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.344619f, 0.362480f, -0.056226f },	{ 0.353908f, 0.425954f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.344619f, 0.362480f, -0.065334f },	{ 0.353908f, 0.114202f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.344619f, 0.372713f, -0.065334f },	{ 0.704151f, 0.114202f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.418517f, 0.372713f, -0.056226f },	{ 0.416505f, 0.906709f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.344619f, 0.372713f, -0.056226f },	{ 0.704153f, 0.425954f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.418517f, 0.362481f, -0.056226f },	{ 0.625317f, 1.440788f, 0.000000f },	{ -0.000000f, -1.000000f, 0.000000f }	},
	{	{ -0.418517f, 0.362481f, -0.065334f },	{ 0.551395f, 1.440788f, 0.000000f },	{ -0.000000f, -1.000000f, 0.000000f }	},
	{	{ -0.344619f, 0.362480f, -0.065334f },	{ 0.551397f, -0.038532f, 0.000000f },	{ -0.000000f, -1.000000f, 0.000000f }	},
	{	{ -0.418517f, 0.372713f, -0.056226f },	{ 0.396389f, 1.440793f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.344619f, 0.372713f, -0.056226f },	{ 0.396390f, -0.038532f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.344619f, 0.372713f, -0.065334f },	{ 0.470309f, -0.038532f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.418517f, 0.362481f, -0.065334f },	{ 0.551395f, 1.440788f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ -0.418517f, 0.372713f, -0.065334f },	{ 0.470497f, 1.440789f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ -0.344619f, 0.372713f, -0.065334f },	{ 0.470498f, -0.038531f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ -0.344619f, 0.372713f, -0.056226f },	{ 0.396390f, -0.038532f, 0.000000f },	{ -0.000000f, 0.000000f, 1.000000f }	},
	{	{ -0.418517f, 0.372713f, -0.056226f },	{ 0.396389f, 1.440793f, 0.000000f },	{ -0.000000f, 0.000000f, 1.000000f }	},
	{	{ -0.418517f, 0.362481f, -0.056226f },	{ 0.315489f, 1.440792f, 0.000000f },	{ -0.000000f, 0.000000f, 1.000000f }	},
	{	{ -0.409923f, 0.371826f, 0.046974f },	{ 0.808810f, 0.999867f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.409923f, 0.371826f, -0.056443f },	{ 0.808578f, 0.323061f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.415263f, 0.371826f, -0.056443f },	{ 0.843525f, 0.323049f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.415263f, 0.353050f, -0.056443f },	{ 0.966401f, 0.323007f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.415263f, 0.353050f, 0.046974f },	{ 0.966634f, 0.999812f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.415263f, 0.371826f, 0.046974f },	{ 0.843757f, 0.999855f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.353030f, 0.371826f, -0.056443f },	{ 0.742700f, 0.000122f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.353030f, 0.371825f, 0.046974f },	{ 0.742699f, 0.676928f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.347690f, 0.371825f, 0.046974f },	{ 0.707752f, 0.676928f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.347690f, 0.371825f, 0.046974f },	{ 0.707752f, 0.676928f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.347690f, 0.353050f, 0.046974f },	{ 0.584876f, 0.676928f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.347690f, 0.353050f, -0.056443f },	{ 0.584876f, 0.000122f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.409923f, 0.366811f, 0.046974f },	{ 0.775994f, 0.999878f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.409923f, 0.366811f, -0.056443f },	{ 0.775760f, 0.323072f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.409923f, 0.371826f, -0.056443f },	{ 0.808578f, 0.323061f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.353030f, 0.371826f, -0.056443f },	{ 0.742700f, 0.000122f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.353030f, 0.366811f, -0.056443f },	{ 0.775515f, 0.000122f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.353030f, 0.366811f, 0.046974f },	{ 0.775517f, 0.676928f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.344619f, 0.362480f, -0.056226f },	{ 0.625317f, -0.038531f, 0.000000f },	{ -0.000000f, -1.000000f, 0.000000f }	},
	{	{ -0.418517f, 0.372713f, -0.065334f },	{ 0.470310f, 1.440793f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.344619f, 0.362480f, -0.065334f },	{ 0.551397f, -0.038532f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ -0.344619f, 0.362480f, -0.056226f },	{ 0.315491f, -0.038532f, 0.000000f },	{ -0.000000f, 0.000000f, 1.000000f }	},
	{	{ -0.415263f, 0.371826f, 0.046974f },	{ 0.843757f, 0.999855f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.415263f, 0.371826f, -0.056443f },	{ 0.843525f, 0.323049f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.347690f, 0.371826f, -0.056443f },	{ 0.707753f, 0.000122f, 0.000000f },	{ 0.000000f, 1.000000f, -0.000000f }	},
	{	{ -0.347690f, 0.371826f, -0.056443f },	{ 0.707753f, 0.000122f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.409923f, 0.371826f, 0.046974f },	{ 0.808810f, 0.999867f, 0.000000f },	{ 1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.353030f, 0.371825f, 0.046974f },	{ 0.742699f, 0.676928f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
};
#define _DoorSideFrame_vertices_
#endif
#ifndef _DoorSideFrame_indices_
// Index Data follows: Sequential by mesh, Every Three Indices == One Triangle.
const unsigned int DoorSideFrame_indices[72] =
{
	 0, 1, 2,
	 3, 4, 5,
	 0, 2, 6,
	 3, 5, 7,
	 8, 9, 10,
	 11, 12, 13,
	 14, 15, 16,
	 17, 18, 19,
	 20, 21, 22,
	 23, 24, 25,
	 26, 27, 28,
	 29, 30, 31,
	 32, 33, 34,
	 35, 36, 37,
	 8, 10, 38,
	 11, 13, 39,
	 14, 16, 40,
	 17, 19, 41,
	 20, 22, 42,
	 23, 25, 43,
	 26, 28, 44,
	 29, 31, 45,
	 32, 34, 46,
	 35, 37, 47,
};
#define _DoorSideFrame_indices_
#endif
// Part of an OBJ_MATERIAL, the struct is 16 byte aligned so it is GPU register friendly.
#ifndef __OBJ_ATTRIBUTES__
typedef struct _OBJ_ATTRIBUTES_
{
	OBJ_VEC3    Kd; // diffuse reflectivity
	float	    d; // dissolve (transparency) 
	OBJ_VEC3    Ks; // specular reflectivity
	float       Ns; // specular exponent
	OBJ_VEC3    Ka; // ambient reflectivity
	float       sharpness; // local reflection map sharpness
	OBJ_VEC3    Tf; // transmission filter
	float       Ni; // optical density (index of refraction)
	OBJ_VEC3    Ke; // emissive reflectivity
	unsigned    illum; // illumination model
}OBJ_ATTRIBUTES;
#define __OBJ_ATTRIBUTES__
#endif
// This structure also has been made GPU register friendly so it can be transfered directly if desired.
// Note: Total struct size will vary depenedening on CPU processor architecture (string pointers).
#ifndef __OBJ_MATERIAL__
typedef struct _OBJ_MATERIAL_
{
	// The following items are typically used in a pixel/fragment shader, they are packed for GPU registers.
	OBJ_ATTRIBUTES attrib; // Surface shading characteristics & illumination model
	// All items below this line are not needed on the GPU and are generally only used during load time.
	const char* name; // the name of this material
	// If the model's materials contain any specific texture data it will be located below.
	const char* map_Kd; // diffuse texture
	const char* map_Ks; // specular texture
	const char* map_Ka; // ambient texture
	const char* map_Ke; // emissive texture
	const char* map_Ns; // specular exponent texture
	const char* map_d; // transparency texture
	const char* disp; // roughness map (displacement)
	const char* decal; // decal texture (lerps texture & material colors)
	const char* bump; // normal/bumpmap texture
	void* padding[2]; // 16 byte alignment on 32bit or 64bit
}OBJ_MATERIAL;
#define __OBJ_MATERIAL__
#endif
#ifndef _DoorSideFrame_materials_
// Material Data follows: pulled from a .mtl file of the same name if present.
const OBJ_MATERIAL DoorSideFrame_materials[2] =
{
	{
		{{ 0.800000f, 0.800000f, 0.800000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		225.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		60.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		1},
		"LogEdgeWeathered",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
	},
	{
		{{ 0.800000f, 0.800000f, 0.800000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		225.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		60.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		1},
		"Wood.002",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
	},
};
#define _DoorSideFrame_materials_
#endif
/************************************************/
/*  This section contains the model's structure */
/************************************************/
#ifndef _DoorSideFrame_batches_
// Use this conveinence array to batch render all geometry by like material.
// Each entry corresponds to the same entry in the materials array above.
// The two numbers provided are the IndexCount and the IndexOffset into the indices array.
// If you need more fine grained control(ex: for transformations) use the OBJ_MESH data below.
const unsigned int DoorSideFrame_batches[2][2] =
{
	{ 12, 0 },
	{ 60, 12 },
};
#define _DoorSideFrame_batches_
#endif
#ifndef __OBJ_MESH__
typedef struct _OBJ_MESH_
{
	const char* name;
	unsigned    indexCount;
	unsigned    indexOffset;
	unsigned    materialIndex;
}OBJ_MESH;
#define __OBJ_MESH__
#endif
#ifndef _DoorSideFrame_meshes_
// Mesh Data follows: Meshes are .obj groups sorted & split by material.
// Meshes are provided in sequential order, sorted by material first and name second.
const OBJ_MESH DoorSideFrame_meshes[2] =
{
	{
		"default",
		12,
		0,
		0,
	},
	{
		"default",
		60,
		12,
		1,
	},
};
#define _DoorSideFrame_meshes_
#endif
