// "DoorFrontFrame.h" generated by "Obj2Header.exe" [Version 1.9d] Author: L.Norri Fullsail University.
// Data is converted to left-handed coordinate system and UV data is V flipped for Direct3D/Vulkan.
// The companion file "DoorFrontFrame.h2b" is a binary dump of this format(-padding) for more flexibility.
// Loading *.h2b: read version, sizes, handle strings(max len 260) by reading until null-terminated.
/***********************/
/*  Generator version  */
/***********************/
#ifndef _DoorFrontFrame_version_
const char DoorFrontFrame_version[4] = { '0','1','9','d' };
#define _DoorFrontFrame_version_
#endif
/************************************************/
/*  This section contains the model's size data */
/************************************************/
#ifndef _DoorFrontFrame_vertexcount_
const unsigned DoorFrontFrame_vertexcount = 48;
#define _DoorFrontFrame_vertexcount_
#endif
#ifndef _DoorFrontFrame_indexcount_
const unsigned DoorFrontFrame_indexcount = 72;
#define _DoorFrontFrame_indexcount_
#endif
#ifndef _DoorFrontFrame_materialcount_
const unsigned DoorFrontFrame_materialcount = 2; // can be used for batched draws
#define _DoorFrontFrame_materialcount_
#endif
#ifndef _DoorFrontFrame_meshcount_
const unsigned DoorFrontFrame_meshcount = 2;
#define _DoorFrontFrame_meshcount_
#endif
/************************************************/
/*  This section contains the raw data to load  */
/************************************************/
#ifndef __OBJ_VEC3__
typedef struct _OBJ_VEC3_
{
	float x,y,z; // 3D Coordinate.
}OBJ_VEC3;
#define __OBJ_VEC3__
#endif
#ifndef __OBJ_VERT__
typedef struct _OBJ_VERT_
{
	OBJ_VEC3 pos; // Left-handed +Z forward coordinate w not provided, assumed to be 1.
	OBJ_VEC3 uvw; // D3D/Vulkan style top left 0,0 coordinate.
	OBJ_VEC3 nrm; // Provided direct from obj file, may or may not be normalized.
}OBJ_VERT;
#define __OBJ_VERT__
#endif
#ifndef _DoorFrontFrame_vertices_
// Raw Vertex Data follows: Positions, Texture Coordinates and Normals.
const OBJ_VERT DoorFrontFrame_vertices[48] =
{
	{	{ 0.656429f, 0.088964f, 0.024666f },	{ 0.999903f, 0.999902f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.671011f, 0.088964f, 0.024666f },	{ 0.372636f, 0.999903f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.671011f, 0.097620f, 0.024666f },	{ 0.372635f, 0.627558f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.671011f, 0.097620f, -0.048193f },	{ 0.006782f, 0.385874f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.671011f, 0.088964f, -0.048193f },	{ 0.039562f, 0.107699f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.656429f, 0.088964f, -0.048193f },	{ 0.872673f, 0.162925f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.656429f, 0.097620f, 0.024666f },	{ 0.999903f, 0.627558f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.656429f, 0.097620f, -0.048193f },	{ 0.839892f, 0.441100f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.656429f, 0.088964f, -0.048193f },	{ 0.396428f, 0.420532f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.656429f, 0.088964f, 0.024666f },	{ 0.396428f, 0.794976f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.656429f, 0.097620f, 0.024666f },	{ 0.354125f, 0.794976f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.656429f, 0.088964f, -0.048193f },	{ 0.396428f, 0.420532f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ 0.671011f, 0.088964f, -0.048193f },	{ 0.467694f, 0.420532f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ 0.671011f, 0.088964f, 0.024666f },	{ 0.467694f, 0.794976f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ 0.656429f, 0.097620f, -0.048193f },	{ 0.311891f, 0.347379f, 0.000000f },	{ 0.000000f, 1.000000f, 0.000000f }	},
	{	{ 0.656429f, 0.097620f, 0.024666f },	{ 0.311889f, 0.721824f, 0.000000f },	{ 0.000000f, 1.000000f, 0.000000f }	},
	{	{ 0.671011f, 0.097620f, 0.024666f },	{ 0.240623f, 0.721823f, 0.000000f },	{ 0.000000f, 1.000000f, 0.000000f }	},
	{	{ 0.671011f, 0.097620f, -0.048193f },	{ 0.240625f, 0.347379f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.671011f, 0.097620f, 0.024666f },	{ 0.240623f, 0.721823f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.671011f, 0.088964f, 0.024666f },	{ 0.198320f, 0.721822f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.669483f, -0.014502f, 0.016768f },	{ 0.808810f, 0.999867f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.669483f, 0.088916f, 0.016768f },	{ 0.808578f, 0.323061f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.669483f, 0.088916f, 0.022108f },	{ 0.843525f, 0.323049f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.650708f, 0.088916f, 0.022108f },	{ 0.966401f, 0.323007f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.650708f, -0.014502f, 0.022108f },	{ 0.966634f, 0.999812f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.669483f, -0.014502f, 0.022108f },	{ 0.843757f, 0.999855f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.669483f, 0.088916f, -0.045466f },	{ 0.707753f, 0.000122f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.669483f, 0.088916f, -0.040126f },	{ 0.742700f, 0.000122f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.669483f, -0.014502f, -0.040126f },	{ 0.742699f, 0.676928f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.669483f, -0.014502f, -0.045466f },	{ 0.707752f, 0.676928f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.650708f, -0.014502f, -0.045466f },	{ 0.584876f, 0.676928f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.650708f, 0.088916f, -0.045466f },	{ 0.584876f, 0.000122f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.664469f, 0.088916f, 0.016768f },	{ 0.775760f, 0.323072f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.669483f, 0.088916f, 0.016768f },	{ 0.808578f, 0.323061f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.669483f, -0.014502f, 0.016768f },	{ 0.808810f, 0.999867f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.664469f, 0.088916f, -0.040126f },	{ 0.775515f, 0.000122f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.664469f, -0.014502f, -0.040126f },	{ 0.775517f, 0.676928f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.669483f, -0.014502f, -0.040126f },	{ 0.742699f, 0.676928f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.656429f, 0.097620f, -0.048193f },	{ 0.354125f, 0.420531f, 0.000000f },	{ -1.000000f, 0.000000f, -0.000000f }	},
	{	{ 0.656429f, 0.088964f, 0.024666f },	{ 0.396428f, 0.794976f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ 0.671011f, 0.097620f, -0.048193f },	{ 0.240625f, 0.347379f, 0.000000f },	{ 0.000000f, 1.000000f, 0.000000f }	},
	{	{ 0.671011f, 0.088964f, -0.048193f },	{ 0.198322f, 0.347379f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.669483f, -0.014502f, 0.022108f },	{ 0.843757f, 0.999855f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.669483f, 0.088916f, 0.022108f },	{ 0.843525f, 0.323049f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
	{	{ 0.669483f, -0.014502f, -0.045466f },	{ 0.707752f, 0.676928f, 0.000000f },	{ 1.000000f, -0.000000f, 0.000000f }	},
	{	{ 0.669483f, 0.088916f, -0.045466f },	{ 0.707753f, 0.000122f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.664469f, -0.014502f, 0.016768f },	{ 0.775994f, 0.999878f, 0.000000f },	{ 0.000000f, 0.000000f, -1.000000f }	},
	{	{ 0.669483f, 0.088916f, -0.040126f },	{ 0.742700f, 0.000122f, 0.000000f },	{ 0.000000f, 0.000000f, 1.000000f }	},
};
#define _DoorFrontFrame_vertices_
#endif
#ifndef _DoorFrontFrame_indices_
// Index Data follows: Sequential by mesh, Every Three Indices == One Triangle.
const unsigned int DoorFrontFrame_indices[72] =
{
	 0, 1, 2,
	 3, 4, 5,
	 0, 2, 6,
	 3, 5, 7,
	 8, 9, 10,
	 11, 12, 13,
	 14, 15, 16,
	 17, 18, 19,
	 20, 21, 22,
	 23, 24, 25,
	 26, 27, 28,
	 29, 30, 31,
	 32, 33, 34,
	 35, 36, 37,
	 8, 10, 38,
	 11, 13, 39,
	 14, 16, 40,
	 17, 19, 41,
	 20, 22, 42,
	 23, 25, 43,
	 26, 28, 44,
	 29, 31, 45,
	 32, 34, 46,
	 35, 37, 47,
};
#define _DoorFrontFrame_indices_
#endif
// Part of an OBJ_MATERIAL, the struct is 16 byte aligned so it is GPU register friendly.
#ifndef __OBJ_ATTRIBUTES__
typedef struct _OBJ_ATTRIBUTES_
{
	OBJ_VEC3    Kd; // diffuse reflectivity
	float	    d; // dissolve (transparency) 
	OBJ_VEC3    Ks; // specular reflectivity
	float       Ns; // specular exponent
	OBJ_VEC3    Ka; // ambient reflectivity
	float       sharpness; // local reflection map sharpness
	OBJ_VEC3    Tf; // transmission filter
	float       Ni; // optical density (index of refraction)
	OBJ_VEC3    Ke; // emissive reflectivity
	unsigned    illum; // illumination model
}OBJ_ATTRIBUTES;
#define __OBJ_ATTRIBUTES__
#endif
// This structure also has been made GPU register friendly so it can be transfered directly if desired.
// Note: Total struct size will vary depenedening on CPU processor architecture (string pointers).
#ifndef __OBJ_MATERIAL__
typedef struct _OBJ_MATERIAL_
{
	// The following items are typically used in a pixel/fragment shader, they are packed for GPU registers.
	OBJ_ATTRIBUTES attrib; // Surface shading characteristics & illumination model
	// All items below this line are not needed on the GPU and are generally only used during load time.
	const char* name; // the name of this material
	// If the model's materials contain any specific texture data it will be located below.
	const char* map_Kd; // diffuse texture
	const char* map_Ks; // specular texture
	const char* map_Ka; // ambient texture
	const char* map_Ke; // emissive texture
	const char* map_Ns; // specular exponent texture
	const char* map_d; // transparency texture
	const char* disp; // roughness map (displacement)
	const char* decal; // decal texture (lerps texture & material colors)
	const char* bump; // normal/bumpmap texture
	void* padding[2]; // 16 byte alignment on 32bit or 64bit
}OBJ_MATERIAL;
#define __OBJ_MATERIAL__
#endif
#ifndef _DoorFrontFrame_materials_
// Material Data follows: pulled from a .mtl file of the same name if present.
const OBJ_MATERIAL DoorFrontFrame_materials[2] =
{
	{
		{{ 0.800000f, 0.800000f, 0.800000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		225.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		60.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		1},
		"LogEdgeWeathered",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
	},
	{
		{{ 0.800000f, 0.800000f, 0.800000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		225.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		60.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		1},
		"Wood.002",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
	},
};
#define _DoorFrontFrame_materials_
#endif
/************************************************/
/*  This section contains the model's structure */
/************************************************/
#ifndef _DoorFrontFrame_batches_
// Use this conveinence array to batch render all geometry by like material.
// Each entry corresponds to the same entry in the materials array above.
// The two numbers provided are the IndexCount and the IndexOffset into the indices array.
// If you need more fine grained control(ex: for transformations) use the OBJ_MESH data below.
const unsigned int DoorFrontFrame_batches[2][2] =
{
	{ 12, 0 },
	{ 60, 12 },
};
#define _DoorFrontFrame_batches_
#endif
#ifndef __OBJ_MESH__
typedef struct _OBJ_MESH_
{
	const char* name;
	unsigned    indexCount;
	unsigned    indexOffset;
	unsigned    materialIndex;
}OBJ_MESH;
#define __OBJ_MESH__
#endif
#ifndef _DoorFrontFrame_meshes_
// Mesh Data follows: Meshes are .obj groups sorted & split by material.
// Meshes are provided in sequential order, sorted by material first and name second.
const OBJ_MESH DoorFrontFrame_meshes[2] =
{
	{
		"default",
		12,
		0,
		0,
	},
	{
		"default",
		60,
		12,
		1,
	},
};
#define _DoorFrontFrame_meshes_
#endif
