// "IronHotEdge2.h" generated by "Obj2Header.exe" [Version 1.9d] Author: L.Norri Fullsail University.
// Data is converted to left-handed coordinate system and UV data is V flipped for Direct3D/Vulkan.
// The companion file "IronHotEdge2.h2b" is a binary dump of this format(-padding) for more flexibility.
// Loading *.h2b: read version, sizes, handle strings(max len 260) by reading until null-terminated.
/***********************/
/*  Generator version  */
/***********************/
#ifndef _IronHotEdge2_version_
const char IronHotEdge2_version[4] = { '0','1','9','d' };
#define _IronHotEdge2_version_
#endif
/************************************************/
/*  This section contains the model's size data */
/************************************************/
#ifndef _IronHotEdge2_vertexcount_
const unsigned IronHotEdge2_vertexcount = 32;
#define _IronHotEdge2_vertexcount_
#endif
#ifndef _IronHotEdge2_indexcount_
const unsigned IronHotEdge2_indexcount = 36;
#define _IronHotEdge2_indexcount_
#endif
#ifndef _IronHotEdge2_materialcount_
const unsigned IronHotEdge2_materialcount = 1; // can be used for batched draws
#define _IronHotEdge2_materialcount_
#endif
#ifndef _IronHotEdge2_meshcount_
const unsigned IronHotEdge2_meshcount = 1;
#define _IronHotEdge2_meshcount_
#endif
/************************************************/
/*  This section contains the raw data to load  */
/************************************************/
#ifndef __OBJ_VEC3__
typedef struct _OBJ_VEC3_
{
	float x,y,z; // 3D Coordinate.
}OBJ_VEC3;
#define __OBJ_VEC3__
#endif
#ifndef __OBJ_VERT__
typedef struct _OBJ_VERT_
{
	OBJ_VEC3 pos; // Left-handed +Z forward coordinate w not provided, assumed to be 1.
	OBJ_VEC3 uvw; // D3D/Vulkan style top left 0,0 coordinate.
	OBJ_VEC3 nrm; // Provided direct from obj file, may or may not be normalized.
}OBJ_VERT;
#define __OBJ_VERT__
#endif
#ifndef _IronHotEdge2_vertices_
// Raw Vertex Data follows: Positions, Texture Coordinates and Normals.
const OBJ_VERT IronHotEdge2_vertices[32] =
{
	{	{ -0.577611f, 0.174728f, 0.030532f },	{ 0.351876f, -0.679454f, 0.000000f },	{ -0.756900f, -0.034700f, 0.652600f }	},
	{	{ -0.578164f, 0.174692f, 0.029889f },	{ 0.351876f, -0.321352f, 0.000000f },	{ -0.756900f, -0.034700f, 0.652600f }	},
	{	{ -0.578028f, 0.172182f, 0.029912f },	{ 0.322493f, -0.321352f, 0.000000f },	{ -0.756900f, -0.034700f, 0.652600f }	},
	{	{ -0.578028f, 0.172182f, 0.029912f },	{ 0.293008f, 0.041576f, 0.000000f },	{ 0.054000f, -0.998500f, 0.009500f }	},
	{	{ -0.551430f, 0.173403f, 0.006983f },	{ 0.917929f, 0.041576f, 0.000000f },	{ 0.054000f, -0.998500f, 0.009500f }	},
	{	{ -0.550877f, 0.173439f, 0.007626f },	{ 0.917929f, 0.399638f, 0.000000f },	{ 0.054000f, -0.998500f, 0.009500f }	},
	{	{ -0.551430f, 0.173403f, 0.006983f },	{ 0.654204f, 0.511096f, 0.000000f },	{ 0.756900f, 0.034700f, -0.652600f }	},
	{	{ -0.551566f, 0.175912f, 0.006959f },	{ 0.683587f, 0.511097f, 0.000000f },	{ 0.756900f, 0.034700f, -0.652600f }	},
	{	{ -0.551013f, 0.175948f, 0.007602f },	{ 0.683587f, 0.869199f, 0.000000f },	{ 0.756900f, 0.034700f, -0.652600f }	},
	{	{ -0.551566f, 0.175912f, 0.006959f },	{ 0.917929f, 0.039170f, 0.000000f },	{ -0.054000f, 0.998500f, -0.009500f }	},
	{	{ -0.578164f, 0.174692f, 0.029889f },	{ 0.293008f, 0.039143f, 0.000000f },	{ -0.054000f, 0.998500f, -0.009500f }	},
	{	{ -0.577611f, 0.174728f, 0.030532f },	{ 0.293008f, -0.318918f, 0.000000f },	{ -0.054000f, 0.998500f, -0.009500f }	},
	{	{ -0.577611f, 0.174728f, 0.030532f },	{ 0.293008f, 1.098762f, 0.000000f },	{ 0.651200f, 0.042400f, 0.757700f }	},
	{	{ -0.577475f, 0.172219f, 0.030556f },	{ 0.293008f, 0.402098f, 0.000000f },	{ 0.651200f, 0.042400f, 0.757700f }	},
	{	{ -0.550877f, 0.173439f, 0.007626f },	{ 0.917902f, 0.402101f, 0.000000f },	{ 0.651200f, 0.042400f, 0.757700f }	},
	{	{ -0.551566f, 0.175912f, 0.006959f },	{ 0.917902f, 1.101170f, 0.000000f },	{ -0.651200f, -0.042400f, -0.757700f }	},
	{	{ -0.551430f, 0.173403f, 0.006983f },	{ 0.917902f, 1.797835f, 0.000000f },	{ -0.651200f, -0.042400f, -0.757700f }	},
	{	{ -0.578028f, 0.172182f, 0.029912f },	{ 0.293008f, 1.797817f, 0.000000f },	{ -0.651200f, -0.042400f, -0.757700f }	},
	{	{ -0.577611f, 0.174728f, 0.030532f },	{ 0.351876f, -0.679454f, 0.000000f },	{ -0.757000f, -0.034700f, 0.652500f }	},
	{	{ -0.578028f, 0.172182f, 0.029912f },	{ 0.322493f, -0.321352f, 0.000000f },	{ -0.757000f, -0.034700f, 0.652500f }	},
	{	{ -0.577475f, 0.172219f, 0.030556f },	{ 0.322493f, -0.679454f, 0.000000f },	{ -0.757000f, -0.034700f, 0.652500f }	},
	{	{ -0.577475f, 0.172219f, 0.030556f },	{ 0.293008f, 0.399691f, 0.000000f },	{ 0.054000f, -0.998500f, 0.009500f }	},
	{	{ -0.551430f, 0.173403f, 0.006983f },	{ 0.654204f, 0.511096f, 0.000000f },	{ 0.757000f, 0.034700f, -0.652500f }	},
	{	{ -0.551013f, 0.175948f, 0.007602f },	{ 0.683587f, 0.869199f, 0.000000f },	{ 0.757000f, 0.034700f, -0.652500f }	},
	{	{ -0.550877f, 0.173439f, 0.007626f },	{ 0.654204f, 0.869199f, 0.000000f },	{ 0.757000f, 0.034700f, -0.652500f }	},
	{	{ -0.551013f, 0.175948f, 0.007602f },	{ 0.917929f, -0.318946f, 0.000000f },	{ -0.054000f, 0.998500f, -0.009500f }	},
	{	{ -0.577611f, 0.174728f, 0.030532f },	{ 0.293008f, 1.098762f, 0.000000f },	{ 0.651200f, 0.042500f, 0.757700f }	},
	{	{ -0.550877f, 0.173439f, 0.007626f },	{ 0.917902f, 0.402101f, 0.000000f },	{ 0.651200f, 0.042500f, 0.757700f }	},
	{	{ -0.551013f, 0.175948f, 0.007602f },	{ 0.917902f, 1.098750f, 0.000000f },	{ 0.651200f, 0.042500f, 0.757700f }	},
	{	{ -0.551566f, 0.175912f, 0.006959f },	{ 0.917902f, 1.101170f, 0.000000f },	{ -0.651200f, -0.042500f, -0.757700f }	},
	{	{ -0.578028f, 0.172182f, 0.029912f },	{ 0.293008f, 1.797817f, 0.000000f },	{ -0.651200f, -0.042500f, -0.757700f }	},
	{	{ -0.578164f, 0.174692f, 0.029889f },	{ 0.293008f, 1.101169f, 0.000000f },	{ -0.651200f, -0.042500f, -0.757700f }	},
};
#define _IronHotEdge2_vertices_
#endif
#ifndef _IronHotEdge2_indices_
// Index Data follows: Sequential by mesh, Every Three Indices == One Triangle.
const unsigned int IronHotEdge2_indices[36] =
{
	 0, 1, 2,
	 3, 4, 5,
	 6, 7, 8,
	 9, 10, 11,
	 12, 13, 14,
	 15, 16, 17,
	 18, 19, 20,
	 3, 5, 21,
	 22, 23, 24,
	 9, 11, 25,
	 26, 27, 28,
	 29, 30, 31,
};
#define _IronHotEdge2_indices_
#endif
// Part of an OBJ_MATERIAL, the struct is 16 byte aligned so it is GPU register friendly.
#ifndef __OBJ_ATTRIBUTES__
typedef struct _OBJ_ATTRIBUTES_
{
	OBJ_VEC3    Kd; // diffuse reflectivity
	float	    d; // dissolve (transparency) 
	OBJ_VEC3    Ks; // specular reflectivity
	float       Ns; // specular exponent
	OBJ_VEC3    Ka; // ambient reflectivity
	float       sharpness; // local reflection map sharpness
	OBJ_VEC3    Tf; // transmission filter
	float       Ni; // optical density (index of refraction)
	OBJ_VEC3    Ke; // emissive reflectivity
	unsigned    illum; // illumination model
}OBJ_ATTRIBUTES;
#define __OBJ_ATTRIBUTES__
#endif
// This structure also has been made GPU register friendly so it can be transfered directly if desired.
// Note: Total struct size will vary depenedening on CPU processor architecture (string pointers).
#ifndef __OBJ_MATERIAL__
typedef struct _OBJ_MATERIAL_
{
	// The following items are typically used in a pixel/fragment shader, they are packed for GPU registers.
	OBJ_ATTRIBUTES attrib; // Surface shading characteristics & illumination model
	// All items below this line are not needed on the GPU and are generally only used during load time.
	const char* name; // the name of this material
	// If the model's materials contain any specific texture data it will be located below.
	const char* map_Kd; // diffuse texture
	const char* map_Ks; // specular texture
	const char* map_Ka; // ambient texture
	const char* map_Ke; // emissive texture
	const char* map_Ns; // specular exponent texture
	const char* map_d; // transparency texture
	const char* disp; // roughness map (displacement)
	const char* decal; // decal texture (lerps texture & material colors)
	const char* bump; // normal/bumpmap texture
	void* padding[2]; // 16 byte alignment on 32bit or 64bit
}OBJ_MATERIAL;
#define __OBJ_MATERIAL__
#endif
#ifndef _IronHotEdge2_materials_
// Material Data follows: pulled from a .mtl file of the same name if present.
const OBJ_MATERIAL IronHotEdge2_materials[1] =
{
	{
		{{ 0.800000f, 0.800000f, 0.800000f },
		1.000000f,
		{ 0.131579f, 0.131579f, 0.131579f },
		225.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		60.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		2},
		"HotIron",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
	},
};
#define _IronHotEdge2_materials_
#endif
/************************************************/
/*  This section contains the model's structure */
/************************************************/
#ifndef _IronHotEdge2_batches_
// Use this conveinence array to batch render all geometry by like material.
// Each entry corresponds to the same entry in the materials array above.
// The two numbers provided are the IndexCount and the IndexOffset into the indices array.
// If you need more fine grained control(ex: for transformations) use the OBJ_MESH data below.
const unsigned int IronHotEdge2_batches[1][2] =
{
	{ 36, 0 },
};
#define _IronHotEdge2_batches_
#endif
#ifndef __OBJ_MESH__
typedef struct _OBJ_MESH_
{
	const char* name;
	unsigned    indexCount;
	unsigned    indexOffset;
	unsigned    materialIndex;
}OBJ_MESH;
#define __OBJ_MESH__
#endif
#ifndef _IronHotEdge2_meshes_
// Mesh Data follows: Meshes are .obj groups sorted & split by material.
// Meshes are provided in sequential order, sorted by material first and name second.
const OBJ_MESH IronHotEdge2_meshes[1] =
{
	{
		"default",
		36,
		0,
		0,
	},
};
#define _IronHotEdge2_meshes_
#endif
