// "Level3.h" generated by "Obj2Header.exe" [Version 1.9d] Author: L.Norri Fullsail University.
// Data is converted to left-handed coordinate system and UV data is V flipped for Direct3D/Vulkan.
// The companion file "Level3.h2b" is a binary dump of this format(-padding) for more flexibility.
// Loading *.h2b: read version, sizes, handle strings(max len 260) by reading until null-terminated.
/***********************/
/*  Generator version  */
/***********************/
#ifndef _Level3_version_
const char Level3_version[4] = { '0','1','9','d' };
#define _Level3_version_
#endif
/************************************************/
/*  This section contains the model's size data */
/************************************************/
#ifndef _Level3_vertexcount_
const unsigned Level3_vertexcount = 14;
#define _Level3_vertexcount_
#endif
#ifndef _Level3_indexcount_
const unsigned Level3_indexcount = 24;
#define _Level3_indexcount_
#endif
#ifndef _Level3_materialcount_
const unsigned Level3_materialcount = 1; // can be used for batched draws
#define _Level3_materialcount_
#endif
#ifndef _Level3_meshcount_
const unsigned Level3_meshcount = 1;
#define _Level3_meshcount_
#endif
/************************************************/
/*  This section contains the raw data to load  */
/************************************************/
#ifndef __OBJ_VEC3__
typedef struct _OBJ_VEC3_
{
	float x,y,z; // 3D Coordinate.
}OBJ_VEC3;
#define __OBJ_VEC3__
#endif
#ifndef __OBJ_VERT__
typedef struct _OBJ_VERT_
{
	OBJ_VEC3 pos; // Left-handed +Z forward coordinate w not provided, assumed to be 1.
	OBJ_VEC3 uvw; // D3D/Vulkan style top left 0,0 coordinate.
	OBJ_VEC3 nrm; // Provided direct from obj file, may or may not be normalized.
}OBJ_VERT;
#define __OBJ_VERT__
#endif
#ifndef _Level3_vertices_
// Raw Vertex Data follows: Positions, Texture Coordinates and Normals.
const OBJ_VERT Level3_vertices[14] =
{
	{	{ -0.505018f, 0.023178f, -0.338582f },	{ -0.546688f, 0.369583f, 0.000000f },	{ -1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.505018f, -0.076822f, -0.338582f },	{ 0.031393f, 0.369583f, 0.000000f },	{ -1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.505018f, -0.076822f, -0.249359f },	{ 0.031392f, 0.895234f, 0.000000f },	{ -1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.436768f, -0.076822f, -0.338582f },	{ 0.446953f, 0.369584f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.436768f, 0.023178f, -0.338582f },	{ 1.025034f, 0.369584f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.436768f, 0.023178f, -0.249359f },	{ 1.025033f, 0.895235f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.505018f, -0.076822f, -0.338582f },	{ 0.031393f, 0.369583f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ -0.470893f, -0.076822f, -0.379395f },	{ 0.239173f, 0.104766f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ -0.470893f, -0.076822f, -0.249359f },	{ 0.239172f, 0.895234f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ -0.436768f, -0.076822f, -0.338582f },	{ 0.446953f, 0.369584f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ -0.436768f, -0.076822f, -0.249359f },	{ 0.446952f, 0.895234f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
	{	{ -0.505018f, 0.023178f, -0.249359f },	{ -0.546689f, 0.895233f, 0.000000f },	{ -1.000000f, -0.000000f, -0.000000f }	},
	{	{ -0.436768f, -0.076822f, -0.249359f },	{ 0.446952f, 0.895234f, 0.000000f },	{ 1.000000f, 0.000000f, -0.000000f }	},
	{	{ -0.505018f, -0.076822f, -0.249359f },	{ 0.031392f, 0.895234f, 0.000000f },	{ 0.000000f, -1.000000f, -0.000000f }	},
};
#define _Level3_vertices_
#endif
#ifndef _Level3_indices_
// Index Data follows: Sequential by mesh, Every Three Indices == One Triangle.
const unsigned int Level3_indices[24] =
{
	 0, 1, 2,
	 3, 4, 5,
	 6, 7, 8,
	 9, 10, 8,
	 0, 2, 11,
	 3, 5, 12,
	 6, 8, 13,
	 9, 8, 7,
};
#define _Level3_indices_
#endif
// Part of an OBJ_MATERIAL, the struct is 16 byte aligned so it is GPU register friendly.
#ifndef __OBJ_ATTRIBUTES__
typedef struct _OBJ_ATTRIBUTES_
{
	OBJ_VEC3    Kd; // diffuse reflectivity
	float	    d; // dissolve (transparency) 
	OBJ_VEC3    Ks; // specular reflectivity
	float       Ns; // specular exponent
	OBJ_VEC3    Ka; // ambient reflectivity
	float       sharpness; // local reflection map sharpness
	OBJ_VEC3    Tf; // transmission filter
	float       Ni; // optical density (index of refraction)
	OBJ_VEC3    Ke; // emissive reflectivity
	unsigned    illum; // illumination model
}OBJ_ATTRIBUTES;
#define __OBJ_ATTRIBUTES__
#endif
// This structure also has been made GPU register friendly so it can be transfered directly if desired.
// Note: Total struct size will vary depenedening on CPU processor architecture (string pointers).
#ifndef __OBJ_MATERIAL__
typedef struct _OBJ_MATERIAL_
{
	// The following items are typically used in a pixel/fragment shader, they are packed for GPU registers.
	OBJ_ATTRIBUTES attrib; // Surface shading characteristics & illumination model
	// All items below this line are not needed on the GPU and are generally only used during load time.
	const char* name; // the name of this material
	// If the model's materials contain any specific texture data it will be located below.
	const char* map_Kd; // diffuse texture
	const char* map_Ks; // specular texture
	const char* map_Ka; // ambient texture
	const char* map_Ke; // emissive texture
	const char* map_Ns; // specular exponent texture
	const char* map_d; // transparency texture
	const char* disp; // roughness map (displacement)
	const char* decal; // decal texture (lerps texture & material colors)
	const char* bump; // normal/bumpmap texture
	void* padding[2]; // 16 byte alignment on 32bit or 64bit
}OBJ_MATERIAL;
#define __OBJ_MATERIAL__
#endif
#ifndef _Level3_materials_
// Material Data follows: pulled from a .mtl file of the same name if present.
const OBJ_MATERIAL Level3_materials[1] =
{
	{
		{{ 0.800000f, 0.800000f, 0.800000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		225.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		60.000000f,
		{ 1.000000f, 1.000000f, 1.000000f },
		1.000000f,
		{ 0.000000f, 0.000000f, 0.000000f },
		1},
		"Plaster",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
	},
};
#define _Level3_materials_
#endif
/************************************************/
/*  This section contains the model's structure */
/************************************************/
#ifndef _Level3_batches_
// Use this conveinence array to batch render all geometry by like material.
// Each entry corresponds to the same entry in the materials array above.
// The two numbers provided are the IndexCount and the IndexOffset into the indices array.
// If you need more fine grained control(ex: for transformations) use the OBJ_MESH data below.
const unsigned int Level3_batches[1][2] =
{
	{ 24, 0 },
};
#define _Level3_batches_
#endif
#ifndef __OBJ_MESH__
typedef struct _OBJ_MESH_
{
	const char* name;
	unsigned    indexCount;
	unsigned    indexOffset;
	unsigned    materialIndex;
}OBJ_MESH;
#define __OBJ_MESH__
#endif
#ifndef _Level3_meshes_
// Mesh Data follows: Meshes are .obj groups sorted & split by material.
// Meshes are provided in sequential order, sorted by material first and name second.
const OBJ_MESH Level3_meshes[1] =
{
	{
		"default",
		24,
		0,
		0,
	},
};
#define _Level3_meshes_
#endif
